---
- name: Install Docker and run MySQL 8
  hosts: all
  become: yes
  vars:
    docker_apt_key_url: https://download.docker.com/linux/ubuntu/gpg
    docker_apt_repository: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    mysql_root_password: "P@ssw0rd"
    mysql_database: "mydb"
    mysql_user: "bbik"
    mysql_password: "P@ssw0rd"
    mysql_container_name: mysql8
    mysql_image: mysql:8.0
    mysql_ports:
      - "3306:3306"

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes
      tags: update

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      tags: install

    - name: Add Docker’s official GPG key
      apt_key:
        url: "{{ docker_apt_key_url }}"
        state: present
      tags: install

    - name: Add Docker APT repository
      apt_repository:
        repo: "{{ docker_apt_repository }}"
        state: present
      tags: install

    - name: Update apt package index after adding Docker repository
      apt:
        update_cache: yes
      tags: update

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
      tags: install

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      tags: service

    - name: Pull MySQL 8 Docker image
      docker_image:
        name: "{{ mysql_image.split(':')[0] }}"
        tag: "{{ mysql_image.split(':')[1] }}"
        source: pull
      tags: docker

    - name: Run MySQL container
      docker_container:
        name: "{{ mysql_container_name }}"
        image: "{{ mysql_image }}"
        state: started
        restart_policy: always
        env:
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
          MYSQL_DATABASE: "{{ mysql_database }}"
          MYSQL_USER: "{{ mysql_user }}"
          MYSQL_PASSWORD: "{{ mysql_password }}"
        ports: "{{ mysql_ports }}"
      tags: docker
